### ISSUE TITLE
Locked up at "Do you want to remove Grub 2?"

### ISSUE THREAD

**Issue by beaucoder** [cerebrux/uCareSystem#2]
Ran uCareSystem in terminal and got the above question. There was a "Yes" box and a "No" box but no way to select either one and then press enter. 

Pressing enter merely entered newlines. Nothing happened. Could not continue. Had to Ctrl + C to exit the terminal. 

How to fix? 
Thanks, 
Ken Wagner

**Comment by cerebrux** [comment]
uCaresystem runs the usual commands like apt, apt-get etc. These system commands may sometimes ask questions and present you a terminal UI. The navigation there is done with tab key
